spring:
    application:
        name: websocket

    data:
        mongodb:
            username: mateo
            password: mateo
            host: localhost
            port: 27017
            database: chat_app
            authentication-database: admin

    server:
        port: 8088